
package za.ac.nwu.wsdl.studentacademicregistration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "studentacademicregistrationservice_client_ep", targetNamespace = "http://nwu.ac.za/wsdl/StudentAcademicRegistration", wsdlLocation = "http://v-soatst-ap-lnx1.nwu.ac.za:8001/soa-infra/services/default/StudentAcademicRegistrationByModuleOffering/StudentAcademicRegistration?wsdl")
public class StudentacademicregistrationserviceClientEp
    extends Service
{

    private final static URL STUDENTACADEMICREGISTRATIONSERVICECLIENTEP_WSDL_LOCATION;
    private final static WebServiceException STUDENTACADEMICREGISTRATIONSERVICECLIENTEP_EXCEPTION;
    private final static QName STUDENTACADEMICREGISTRATIONSERVICECLIENTEP_QNAME = new QName("http://nwu.ac.za/wsdl/StudentAcademicRegistration", "studentacademicregistrationservice_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://v-soatst-ap-lnx1.nwu.ac.za:8001/soa-infra/services/default/StudentAcademicRegistrationByModuleOffering/StudentAcademicRegistration?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTACADEMICREGISTRATIONSERVICECLIENTEP_WSDL_LOCATION = url;
        STUDENTACADEMICREGISTRATIONSERVICECLIENTEP_EXCEPTION = e;
    }

    public StudentacademicregistrationserviceClientEp() {
        super(__getWsdlLocation(), STUDENTACADEMICREGISTRATIONSERVICECLIENTEP_QNAME);
    }

    public StudentacademicregistrationserviceClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTACADEMICREGISTRATIONSERVICECLIENTEP_QNAME, features);
    }

    public StudentacademicregistrationserviceClientEp(URL wsdlLocation) {
        super(wsdlLocation, STUDENTACADEMICREGISTRATIONSERVICECLIENTEP_QNAME);
    }

    public StudentacademicregistrationserviceClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTACADEMICREGISTRATIONSERVICECLIENTEP_QNAME, features);
    }

    public StudentacademicregistrationserviceClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentacademicregistrationserviceClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentAcademicRegistrationService
     */
    @WebEndpoint(name = "StudentAcademicRegistrationService_pt")
    public StudentAcademicRegistrationService getStudentAcademicRegistrationServicePt() {
        return super.getPort(new QName("http://nwu.ac.za/wsdl/StudentAcademicRegistration", "StudentAcademicRegistrationService_pt"), StudentAcademicRegistrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentAcademicRegistrationService
     */
    @WebEndpoint(name = "StudentAcademicRegistrationService_pt")
    public StudentAcademicRegistrationService getStudentAcademicRegistrationServicePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://nwu.ac.za/wsdl/StudentAcademicRegistration", "StudentAcademicRegistrationService_pt"), StudentAcademicRegistrationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTACADEMICREGISTRATIONSERVICECLIENTEP_EXCEPTION!= null) {
            throw STUDENTACADEMICREGISTRATIONSERVICECLIENTEP_EXCEPTION;
        }
        return STUDENTACADEMICREGISTRATIONSERVICECLIENTEP_WSDL_LOCATION;
    }

}
