
package za.ac.nwu.wsdl.studentacademicregistration;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MissingParameter", targetNamespace = "http://nwu.ac.za/wsdl/StudentAcademicRegistration")
public class MissingParameterException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MissingParameter faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MissingParameterException(String message, MissingParameter faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MissingParameterException(String message, MissingParameter faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: za.ac.nwu.wsdl.studentacademicregistration.MissingParameter
     */
    public MissingParameter getFaultInfo() {
        return faultInfo;
    }

}
